### DISCUSSION TITLE
Unexpected error encountered: HttpError: Not Found when using "delete-env"

### DISCUSSION THREAD

**Discussion by jessebye** [bobheadxi/deployments#91] [Help]
I am getting an error `Unexpected error encountered: HttpError: Not Found` during the `delete-env` step.

Here's the full logs:

```
Run bobheadxi/deployments@v1.1.0
  with:
    step: delete-env
    token: ***
    desc: Environment was pruned
    env: pulumi-service-pr-51
    debug: true
    auto_inactive: false
targeting <redacted>/pulumi-service
'delete-env' arguments {
  coreArgs: {
    environment: 'pulumi-service-pr-51',
    description: 'Environment was pruned',
    logsURL: 'https://github.com/<redacted>/pulumi-service/commit/0f30981[2](https://github.com/<redacted>/pulumi-service/runs/5382231462?check_suite_focus=true#step:6:2)984b6eacbe7ee8f89ce5d9da2[3](https://github.com/<redacted>/pulumi-service/runs/5382231462?check_suite_focus=true#step:6:3)0a3b30/checks'
  }
}
unexpected error encountered: HttpError: Not Found
Error: unexpected error encountered: HttpError: Not Found - see logs for more information
```

Not sure why this is happening? I can confirm that a deployment matching that environment *does* exist for this repo.

**Comment by bobheadxi** [comment]
This seems to be a permissions issue - see: https://github.com/bobheadxi/deployments/discussions/85

**Reply by jessebye** [reply]
@bobheadxi strange. I can use an alternate GitHub action to inactivate/delete the deployments and environment fine:

```
    - name: Clean up deployments
      uses: strumwolf/delete-deployment-environment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: ${{ github.event.client_payload.environment }}
```

This is the same `GITHUB_TOKEN` I was using for your action. Do you still think it's permissions-related?
