### ISSUE TITLE
Status of branch was not updated

### ISSUE THREAD

**Issue by ai** [bobheadxi/deployments#114]
Deployment was created in Environments, but I still have `This branch has not been deployed` in the pull request

![Снимок экрана от 2022-08-12 03-03-17](https://user-images.githubusercontent.com/19343/184266730-8a5d6037-b729-4cfb-a847-66802eb4045c.png)

```yml
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Notify about new deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview-${{ github.event.number }}
      - name: Deploy files
        id: deploy
        …
      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ steps.deploy.outputs.url }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
```
