### ISSUE TITLE
`step: delete-env` does not delete env

### ISSUE THREAD

**Issue by ai** [bobheadxi/deployments#118]
I [create](https://github.com/browserslist/browsersl.ist/blob/main/.github/workflows/preview.yml#L12-L19) env by

```yml
      - name: Notify about new deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          env: preview-${{ github.event.number }}
```

Then I [delete](https://github.com/browserslist/browsersl.ist/blob/main/.github/workflows/close.yml#L12-L17) it by:

```yml
      - name: Clean from GitHub
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview-${{ github.event.number }}
```

But `delete-env` does not really delete env and only mark it as `inactive`.

Here is a log from GitHub Actions:

```
Run bobheadxi/deployments@v1
  with:
    step: delete-env
    token: ***
    env: preview-479
    debug: false
    auto_inactive: false
targeting ***/browsersl.ist
preview-479: found 1 existing deployments for env
preview-479.642582676: setting deployment (b04ae51d657ee0d1f192d7ae2659b791cbacc38b) state to "inactive"
preview-479: 1 deployments updated
preview-479.642582676: deleting deployment (b04ae51d657ee0d1f192d7ae2659b791cbacc38b)"
preview-479: 1 deployments deleted
```

But we still have `preview-479` in the Environments page in Settings:

![Снимок экрана от 2022-09-05 14-02-39](https://user-images.githubusercontent.com/19343/188444544-74c5ddc9-c2d5-41a2-9182-39a40ae0fcf9.png)
