### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by jillesmc** [bobheadxi/deployments#123]
Recently this action started to indicate the following warning message.

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

I found the solution in this discussion
https://github.com/orgs/community/discussions/35994

Basically you should output to $GITHUB_OUTPUT and stop using set-output command.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

Example:
```YAML
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
```
