### ISSUE TITLE
Recently I've been seeing  Warnings

### ISSUE THREAD

**Issue by zzarbi** [bobheadxi/deployments#14]
<img width="1430" alt="Screen Shot 2020-05-30 at 3 10 07 PM" src="https://user-images.githubusercontent.com/534973/83339950-ab831280-a287-11ea-920a-f02adcb897bc.png">
^ You can ignore the red error one, that's mine. Here's how I use deployment:

```yml
      - name: Flag Deployment in Github
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: staging
```
and
```
      - name: Close deployment
        uses: bobheadxi/deployments@master
        with:
          step: finish
          status: success
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ needs.deploy_staging.outputs.deployment_id }}
```

**Comment by bobheadxi** [comment]
Thanks for pointing this out @zzarbi - it looks like GitHub has started making use of defined parameters in [`action.yml`](https://github.com/bobheadxi/deployments/blob/master/action.yml)...

I'll update this soon to define all the optional params in the file, which *should* make the issue go away - I'll ping back on this ticket when I get to that!

(aside: I never defined everything in `action.yml` because it felt kind of pointless - you define parameters and docs, but they don't get rendered anywhere, which means I have to write it all out again in the README, but I digress 🙃 )

**Comment by munjalpatel** [comment]
@bobheadxi any updates here? I am also running into this issue.

**Comment by maslick** [comment]
I'm seeing this:
```
Warning: Unexpected input(s) 'env', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref']
Warning: Unexpected input(s) 'status', 'env_url', 'deployment_id', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref']
```

```
- name: Start deployment
  uses: bobheadxi/deployments@v0.4.2
  id: deployment
  with:
    step: start
    token: ${{ secrets.GITHUB_TOKEN }}
    env: prod
    ref: ${{ github.head_ref }}
- name: Update deployment status
  uses: bobheadxi/deployments@v0.4.2
  if: always()
  with:
    step: finish
    token: ${{ secrets.GITHUB_TOKEN }}
    status: ${{ job.status }}
    env_url: https://${{ env.domain }}/
    deployment_id: ${{ steps.deployment.outputs.deployment_id }}
```
