### ISSUE TITLE
Add docs about permissions to fine-grained token

### ISSUE THREAD

**Issue by ai** [bobheadxi/deployments#145]
I created fine-grained token with access to a website repo and with `deployments`, `environments`, `metadata`, and `content` permissions.

But it [failed](https://github.com/browserslist/browsersl.ist/actions/runs/4443066402/jobs/7799962597) on `delete-env` step because of the lack of permissions:

```
Run bobheadxi/deployments@v1
targeting ***/browsersl.ist
preview-490: found 2 existing deployments for env
preview-490.834080669: setting deployment (f188baad63570c539de0822405606d801f406259) state to "inactive"
preview-490.834079597: setting deployment (d30b4dddb858ef072d94955b8556f80ab0967443) state to "inactive"
preview-490: 2 deployments updated
preview-490.834080669: deleting deployment (f188baad63570c539de0822405606d801f406259)"
preview-490.834079597: deleting deployment (d30b4dddb858ef072d94955b8556f80ab0967443)"
preview-490: 2 deployments deleted
unexpected error encountered: HttpError: Resource not accessible by personal access token
Error: unexpected error encountered: HttpError: Resource not accessible by personal access token - see logs for more information
```

Here is a config:

```yml
name: Clean Preview
on:
  pull_request:
    types: [ closed ]
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Clean from GitHub
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ secrets.DEPLOYMENTS_TOKEN }}
          env: preview-${{ github.event.number }}
```
