### ISSUE TITLE
Input required and not supplied: deployment_id

### ISSUE THREAD

**Issue by drewbietron** [bobheadxi/deployments#161]
I am updating this to version 1 and am having trouble with the deployment_id. I have tried many combinations of values for it and I cannot seem to get this to work.  I have tried (or thought I did) what the docs explain, as well as trying other values.  The closest I've got is just by hardcoding a value (eg 123) as the deployment_id, but that throws other errors.

Here is my current config
```
 steps:
      - uses: actions/checkout@v3
      - name: Start Web Preview Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ fromJSON('["Production", "Preview"]')[github.ref != 'refs/heads/main'] }}
          deployment_id: ${{ github.event.deployment.id }}
      - name: Web Preview Build
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Deploy
        ... deploy steps
      - name: Update Web Preview Deployment Status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ fromJSON('["Production", "Preview"]')[github.ref != 'refs/heads/main'] }}
          deployment_id: ${{ github.event.deployment.id }}
          debug: true
```

The output for the debug is 
```
Run bobheadxi/deployments@v1
  with:
    step: finish
    token: ***
    status: failure
    env: Preview
    debug: true
    auto_inactive: false
```
deployment_id isnt there.  Its there if I hard code 123 but my suspicion is that what Im using for the deployment_id isnt a thing.

Any help would be appreciated 🙏

**Comment by abivolmv** [comment]
Try using `deployment_id: ${{ steps.deployment.outputs.deployment_id }}`

```
      - name: update deployment status
        uses: bobheadxi/deployments@v1.4.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
```

**Comment by BagasNS** [comment]
> Try using `deployment_id: ${{ steps.deployment.outputs.deployment_id }}`
> 
> ```
>       - name: update deployment status
>         uses: bobheadxi/deployments@v1.4.0
>         if: always()
>         with:
>           step: finish
>           token: ${{ secrets.GITHUB_TOKEN }}
>           status: ${{ job.status }}
>           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
>           env: ${{ steps.deployment.outputs.env }}
> ```

im facing same issue, and still get same error even using your solution

**Comment by abivolmv** [comment]
This is what I use now and it works (must be in the same job):

```yml
      - name: start deployment
        uses: bobheadxi/deployments@v1.5.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.event.inputs.env }}
```
then lower in the same job
```yml
      - name: update deployment status
        uses: bobheadxi/deployments@v1.5.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
```
