### ISSUE TITLE
Deployment not associating with PR

### ISSUE THREAD

**Issue by digitaljohn** [bobheadxi/deployments#30]
First off... love this action. I've been using it across all projects since I came across it with zero issues.

I'm working on a new pipeline which is slightly different to my usual. These are the core differences I can identity:

1. There are 4 different jobs. Two of them deploy to different environments (cms and frontend), each with their own `start` and `finish` steps.
2. I'm using this single pipeline yaml file to handle both `push` and `pull_request` triggers. E.g.
```yaml
on:
  push:
    branches:
      - master
      - qa
      - stage
      - production
  pull_request:
    branches:
      - master
```

The actual **environments** are showing up 100% fine within GitHub (outside of the Pull Request) but within the PR it's reporting no deployments:
![image](https://user-images.githubusercontent.com/1425921/115637193-7a7c5800-a307-11eb-9822-c7dc2da88afc.png)

Could you provide any insights into why this may be happening? Thanks!
