### ISSUE TITLE
make ref configurable

### ISSUE THREAD

**Issue by LilithWittmann** [bobheadxi/deployments#4]
In some cases (e.g. deployment on pr) you want to set the ref to the pr so that the deployment will be displayed in your pr. Therefore it would be cool if the ref could be configured.

**Comment by bobheadxi** [comment]
Hm, does having the deployment display on your PR now work out of the box currently? I am currently using this as [outlined in this blog post](https://dev.to/bobheadxi/branch-previews-with-google-app-engine-and-github-actions-3pco#github-deployments) and my deployments do show up on my PRs properly (link has screenshots)

Do you mind sharing your current setup?

**Comment by LilithWittmann** [comment]
Thanks for the fast response. My current action looks something like this:
```
name: BuildAndDeployDevBranch

on: [pull_request]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '13'
    - run: git submodule init
    - run: git submodule update
    - run: npm ci
    - run: npm run build
#     - run: cp -r ./dist/dev appengine/frontend/static/
    - name: Extract branch name
      id: get_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr / - | tr _ -)"
    - run: echo ${{ steps.get_branch.outputs.branch }}
    - name: start deployment
      uses: bobheadxi/deployments@master
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: ${{ steps.get_branch.outputs.branch }}
        desc: Setting up staging deployment for ${{ steps.get_branch.outputs.branch }}
    - name: deploy to gcloud dev branch
      uses: actions-hub/gcloud@271.0.0
      env:
        PROJECT_ID: something-something
        APPLICATION_CREDENTIALS: ${{ secrets.SA_GOOGLE_APPS_DEPLOY }}
      with:
        args: app deploy app.yaml --no-promote --version ${{ steps.get_branch.outputs.branch }}
    - name: update deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        env: ${{ steps.deployment.outputs.env }}
        env_url: https://${{ steps.get_branch.outputs.branch }}-something-something.appspot.com
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}```

Note: I  only want to deploy in PRs and everything looks fine… except that the deployments are not shown in the github deployment card…

**Comment by bobheadxi** [comment]
I don't see anything wrong with your setup 🤔 Do you mind posting the logs for the `start deployment` step? It seems the deployment isn't getting successfully being created at all, otherwise it should show up on the card as "deployment in progress"

**Comment by LilithWittmann** [comment]
Sure!
<img width="768" alt="Screenshot 2020-01-04 at 01 59 55" src="https://user-images.githubusercontent.com/891030/71757415-16295100-2e96-11ea-8218-ce822bbff9cc.png">

**Comment by bobheadxi** [comment]
That's very strange... thanks for reporting this! Unfortunately won't be able to look into this too closely immediately but I'll see if I can figure it out this weekend

**Comment by xt0rted** [comment]
I'm triggering my PR deploys from Slack and the notification shows as expected (https://github.com/xt0rted/actions-cake-demo/pull/6#event-2872382897). I think this is happening because of the different values `GITHUB_REF` can be set to depending on the event that triggered it.

The docs say a [deployment ](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#deployment-event-deployment) event will set the ref to the `Branch or tag to be deployed (empty if commit)` (`origin/xt0rted-patch-2` in my example PR), while a [pull_request](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request) event will set the ref to the `PR merge branch refs/pull/:prNumber/merge` (`pull/6/merge` in my example PR).

**Comment by LilithWittmann** [comment]
Do you have any updates on this yet? :-)

**Comment by bobheadxi** [comment]
I think @xt0rted is right - I will attempt to patch this behaviour. With my own configuration, which uses `push`, the action works as expected:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/23356519/72117116-5a3aac80-3301-11ea-8c8e-8136e89d0646.png">

Here is my configuration:

```yml
name: appengine-stage

on:
  push:
    branches:
    - master
    # insert branches to stage here
    - finances-frontend-update

jobs:
  stage:
    runs-on: ubuntu-latest
    env: ...

    steps:
    - name: Extract branch name
      id: get_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

    - uses: bobheadxi/deployments@master
      id: deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        step: start
        env: stage-${{ steps.get_branch.outputs.branch }}
        transient: true
        desc: Setting up staging deployment for ${{ steps.get_branch.outputs.branch }}

    - uses: actions/checkout@v1

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}

    # do deploy
    - run: gcloud app deploy client/app.yaml server/app.yaml --no-promote --quiet --version stage-${{ steps.get_branch.outputs.branch }}

    - name: Update deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        step: finish
        status: ${{ job.status }}
        env: ${{ steps.deployment.outputs.env }}
        env_url: https://stage-${{ steps.get_branch.outputs.branch }}-<...>
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
```
